version: '3.1'

services:
  haproxy:
    build: 'haproxy'
    ports:
      - 5432:5432
      - 7000:7000
    depends_on:
      - zoo1
      - pg-master
      - pg-slave

  zoo1:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  pg-master:
    build: 'postgres'
    restart: always
    hostname: pg-master
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - 5432
      - 8008
    ports:
      - 5433:5432
    volumes:
     - '/var/lib/postgresql/data'
    command: su - postgres -c 'patroni /postgres0.yml'

  pg-slave:
    build: 'postgres'
    restart: always
    hostname: pg-slave
    expose:
      - 5432
      - 8008
    ports:
      - 5434:5432
    volumes:
     - '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      #REPLICATE_FROM: 'pg-master'
    command: su - postgres -c 'patroni /postgres1.yml'
